name: "${project.parent.name}"
version: "${project.version}${version.suffix}"
main: ninja.leaping.permissionsex.bukkit.PermissionsExPlugin
api-version: 1.13

commands:
    permissionsex:
        aliases: ["pex"]
        description: Command for PermissionsEx
    promote:
        aliases: ["prom", "rankup"]
        description: Promote a user
    demote:
        aliases: ["dem", "rankdown"]
        description: Demote a user
